name: Lua Example

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
      - name: Install LuaSocket
        run: luarocks install luasocket